#!/usr/bin/env bash
set -euo pipefail

resolve_xdg_dir() {
  local kind="$1"

  if command -v xdg-user-dir >/dev/null 2>&1; then
    xdg-user-dir "$kind" 2>/dev/null && return 0
  fi

  if [[ -f "$HOME/.config/user-dirs.dirs" ]]; then
    # user-dirs.dirs contains simple variable assignments generated by xdg-user-dirs.
    # shellcheck disable=SC1090
    source "$HOME/.config/user-dirs.dirs"
  fi

  case "$kind" in
    PICTURES)
      printf '%s\n' "${XDG_PICTURES_DIR:-$HOME/Pictures}"
      ;;
    VIDEOS)
      printf '%s\n' "${XDG_VIDEOS_DIR:-$HOME/Videos}"
      ;;
    *)
      return 1
      ;;
  esac
}

command -v grim >/dev/null 2>&1 || {
  notify-send "Capture" "grim is not installed"
  exit 1
}

PICTURES_DIR="$(resolve_xdg_dir PICTURES)"
PICTURES_DIR="${PICTURES_DIR%/}/Screenshots"
mkdir -p "$PICTURES_DIR"

timestamp="$(date +%F-%T)"
outfile="$PICTURES_DIR/screenshot-${timestamp}.png"

if command -v slurp >/dev/null 2>&1; then
  region="$(slurp 2>/dev/null || true)"
  [[ -n "${region:-}" ]] || exit 0
  grim -g "$region" "$outfile"
else
  grim "$outfile"
fi

if command -v wl-copy >/dev/null 2>&1; then
  if wl-copy --type image/png <"$outfile"; then
    notify-send "Capture" "Screenshot saved to $outfile and copied to clipboard"
  else
    notify-send "Capture" "Screenshot saved to $outfile; clipboard copy failed"
  fi
else
  notify-send "Capture" "Screenshot saved to $outfile; wl-copy is not installed"
fi
