#!/usr/bin/env bash
set -euo pipefail

resolve_xdg_dir() {
  local kind="$1"

  if command -v xdg-user-dir >/dev/null 2>&1; then
    xdg-user-dir "$kind" 2>/dev/null && return 0
  fi

  if [[ -f "$HOME/.config/user-dirs.dirs" ]]; then
    # user-dirs.dirs contains simple variable assignments generated by xdg-user-dirs.
    # shellcheck disable=SC1090
    source "$HOME/.config/user-dirs.dirs"
  fi

  case "$kind" in
    PICTURES)
      printf '%s\n' "${XDG_PICTURES_DIR:-$HOME/Pictures}"
      ;;
    *)
      return 1
      ;;
  esac
}

command -v grim >/dev/null 2>&1 || {
  notify-send "Capture" "grim is not installed"
  exit 1
}

command -v swaymsg >/dev/null 2>&1 || {
  notify-send "Capture" "swaymsg is not available"
  exit 1
}

command -v jq >/dev/null 2>&1 || {
  notify-send "Capture" "jq is not installed"
  exit 1
}

PICTURES_DIR="$(resolve_xdg_dir PICTURES)"
PICTURES_DIR="${PICTURES_DIR%/}/Screenshots"
mkdir -p "$PICTURES_DIR"

region="$(
  swaymsg -t get_tree 2>/dev/null | jq -r '
    first(.. | objects | select(.focused? == true) | .rect? | select(.width > 0 and .height > 0) | "\(.x),\(.y) \(.width)x\(.height)")
  '
)"

[[ -n "${region:-}" && "$region" != "null" ]] || {
  notify-send "Capture" "Unable to determine active window"
  exit 1
}

timestamp="$(date +%F-%T)"
outfile="$PICTURES_DIR/window-${timestamp}.png"
grim -g "$region" "$outfile"
notify-send "Capture" "Active window saved to $outfile"
