#!/usr/bin/env bash
set -euo pipefail

if [[ -x /usr/share/code/code ]]; then
  exec /usr/share/code/code --password-store=gnome-libsecret "$@"
fi

if [[ -x /usr/bin/code ]]; then
  exec /usr/bin/code --password-store=gnome-libsecret "$@"
fi

printf '[vscode] Visual Studio Code binary not found\n' >&2
exit 127
