# source:target
# source is relative to dotfiles/
# target is relative to ~/.config/
sway:sway
waybar:waybar
mako:mako
swaync:swaync
wofi:wofi
fuzzel:fuzzel
kitty:kitty
wlogout:wlogout
zsh:zsh
fastfetch:fastfetch
atuin:atuin
environment.d:environment.d
scripts:scripts
xdg-desktop-portal:xdg-desktop-portal
mimeapps.list:mimeapps.list
